module.exports = {
	"photos" : [
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8129.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8130.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8131.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8132.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8133.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8134.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8135.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8136.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8137.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8138.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8139.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8140.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8141.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8142.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8143.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8144.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8145.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8146.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8147.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8148.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8149.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8150.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8151.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8152.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8153.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8154.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8155.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8156.JPG",
		"https://housephotostrulia.s3-us-west-1.amazonaws.com/House2/IMG_8157.JPG"
	],
	"id" : 2,
	"topHeaders" : {
		"forSale" : false,
		"forRent" : true,
		"underConstruction" : true,
		"pending" : false,
		"isNew" : true
	},
	"address" : "17389 Daisha Point, North Alecchester Washington, 91872",
	"price" : 260000,
	"saved" : false,
	"bedroom" : 7,
	"bathroom" : 2
}
